### ISSUE TITLE
rpy2 error during logging of following log message with the level warning 

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#217]
When running test for the R stat models following error during logging occurs:
`pytest tests/unittests/mapping_saturation/test_models.py`
```
[...]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.10/logging/__init__.py", line 1101, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/matthias/.cache/pypoetry/virtualenvs/ohsome-quality-analyst-JhxvPu0L-py3.10/lib64/python3.10/site-packages/rpy2/rinterface_lib/embedded.py", line 186, in endr
    rlib.Rf_endEmbeddedR(fatal)
  File "/home/matthias/.cache/pypoetry/virtualenvs/ohsome-quality-analyst-JhxvPu0L-py3.10/lib64/python3.10/site-packages/rpy2/rinterface_lib/callbacks.py", line 137, in _consolewrite_ex
    consolewrite_warnerror(s)
  File "/home/matthias/.cache/pypoetry/virtualenvs/ohsome-quality-analyst-JhxvPu0L-py3.10/lib64/python3.10/site-packages/rpy2/rinterface_lib/callbacks.py", line 123, in consolewrite_warnerror
    logger.warning(_WRITECONSOLE_EXCEPTION_LOG, s)
Message: 'R[write to console]: %s'
Arguments: (' library ‘/usr/share/R/library’ contains no packages\n',)
```

The error during logging does not occur when using Pythons built-in unittest module:
`python -m unittest tests/unittests/mapping_saturation/test_models.py`
```
.2021-12-28 08:48:23,358 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: Waiting for profiling to be done...

.2021-12-28 08:48:23,908 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: Waiting for profiling to be done...

.2021-12-28 08:48:24,430 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: Waiting for profiling to be done...

.2021-12-28 08:48:24,982 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: Waiting for profiling to be done...

.
----------------------------------------------------------------------
Ran 5 tests in 2.355s

OK
2021-12-28 08:48:25,057 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: Warning messages:

2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: 1:
2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:

2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:  library ‘/usr/share/R/library’ contains no packages

2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: 2:
2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
2021-12-28 08:48:25,058 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:

2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:  library ‘/usr/share/R/library’ contains no packages

2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: 3:
2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:

2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:  library ‘/usr/share/R/library’ contains no packages

2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: 4:
2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:

2021-12-28 08:48:25,059 - WARNING - callbacks.py - consolewrite_warnerror - R[write to console]:  library ‘/usr/share/R/library’ contains no packages
```

Expected is first no logging error when running tests with pytest, second no warning message for `library ‘/usr/share/R/library’ contains no packages` since the used R code does not depend on anymore R libraries installed (R-base/R-core should be enough). This error message goes away if a single R library will be installed.

**Comment by matthiasschaub** [comment]
https://github.com/rpy2/rpy2/issues/543

**Comment by matthiasschaub** [comment]
Running tests for `rpy2` does run "successfully"
```
pytest --pyargs 'rpy2.tests'
=============================================== 1 failed, 693 passed, 81 skipped, 2 xfailed, 1 xpassed, 10 warnings in 12.80s ================================================
```
The one error is related to `test_pandas_conversions.py`.
No error during logging occurs.

**Comment by matthiasschaub** [comment]
#170
