### ISSUE TITLE
Database: duplicate key error

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-analyst#570]
We are currently experiencing this issue:

Request:
```
curl -X 'POST' \
  'http://localhost:8080/reports/road-report' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "dataset": "regions",
  "feature-id": 12,
  "fid-field": "ogc_fid",
  "include-svg": false,
  "include-html": false,
  "flatten": false
}'
```

Response:
```
500 Internal Server Error
```

**But you don't get an error if you execute the cURL command a second time.**

OQT log:
<details>
```
INFO:     127.0.0.1:38400 - "POST /reports/road-report HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".../lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File ".../lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File ".../lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File ".../lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File ".../lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File ".../lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File ".../lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File ".../lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/api/api.py", line 281, in post_report
    geojson_object = await oqt.create_report_as_geojson(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/oqt.py", line 138, in create_report_as_geojson
    report = await create_report(parameters, key, force)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/oqt.py", line 318, in _
    report.indicators = await gather_with_semaphore(tasks)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/utils/helper_asyncio.py", line 15, in gather_with_semaphore
    return await asyncio.gather(*(sem_task(task) for task in tasks), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/utils/helper_asyncio.py", line 13, in sem_task
    return await task
           ^^^^^^^^^^
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/oqt.py", line 200, in _
    await db_client.save_indicator_results(indicator, dataset, feature_id)
  File ".../ohsome-quality-analyst/workers/ohsome_quality_analyst/geodatabase/client.py", line 89, in save_indicator_results
    await conn.execute(create_query)
  File ".../lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 338, in query
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(results, 2200) already exists.
```
</details>

**Comment by matthiasschaub** [comment]
This happens only if the database is newly built. Instead of investigating further, I rather would rather wait until we discontinue support of saving indicator results in the database.
